name: emoji_picker_plus
description: Cross‑platform Flutter emoji picker with search, recent, and skin‑tone support.
version: 0.1.0
repository: https://github.com/yourname/emoji_picker_plus
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  shared_preferences: ^2.2.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
